---
config:
  theme: neutral
  layout: elk
title: LIQUIDO - Use Cases
---
flowchart TB
    Welcome("<pre><b>/welcome</b></pre> Register as a new user") 
    --> NickNameInput["NickNameInput"]
    --> CreateOrJoinTeam{{"Crete new team or
Join a team?"}}
    CreateOrJoinTeam -- Create new team --> CreateTeamInput["TeamName
E-Mail
Password"]
    CreateOrJoinTeam -- Join a team --> JoinTeamInput["InviteCode
E-Mail
Password"]
    JoinTeam("<pre><b>/joinTeam?inviteCode=...</b></pre> Join an existing team with an inviteCode. A user can join more than one team!") 
    --> JoinTeamInput    
    CreateTeamInput & JoinTeamInput
    --> RegisterPasskey["Register Passkey<br>(if device supports it)"]
    --> NewUserRegistered

    Login("<pre><b>/login</b></pre>")
    --> LoginInput["Username & password<br>or KeePass"]
    --> LoggedIn

    Index("<pre><b>/</b></pre>") 
    --> IsAuthenticated{{"Is authenticated?"}}
    IsAuthenticated == Yes ==> TeamHome
    IsAuthenticated -- No --> Login
    TeamHome("<pre><b>/team</b></pre> Team Homepage")
    ==> Polls("<pre><b>/polls</b></pre> List of polls of this team")
    ==> PollShow("<pre><b>/polls/:id</b></pre> Show one poll")
    ==> PollStatus{{"Poll status?"}}

    PollStatus -- FINISHED --> ShowWinner["Finished poll\nShow winner"]
    PollStatus -- IN_ELABORATION --> PollInElaboration
    PollStatus -- IN VOTING --> PollInVoting
    

    PollInVoting
    ==> CastVote("<pre><b>/polls/:id/castVote</b></pre> Cast vote in a poll")
    ==> CastVoteInput["User sorts all proposals into his preferred order and then casts his vote."]
    ==> BallotCasted
    
    PollCreate("<pre><b>/poll/create</b></pre>Create a new poll") 
    --> PollTitleInput("Admin sets a poll title\nand saves poll.")
    --> PollInElaboration(["Poll in ELABORATION"])
    --> AddProposal("<pre><b>/polls/:id/add</b></pre> Every Team member can add a proposals with descriptions") 
    --> StartVoting
    --> PollInVoting(["Poll in VOTING<br>Team members can now cast their votes"])
    --> EndVoting
    --> PollFinished

    CreatePolly("<pre><b>/polly</b></pre>")
    --> AddPollyOptions["Polly Admin sets title\nand adds options"]
    --> ClickCreatePasskey["Admin creates his Passkey"]
    --> PollyCreated(["New polly is created and started. Members can immideately cast votes."])
    --> SharePollyLink["Admin share polly link\nto friends"]
    --> FriendsVoteInPolly["<pre><b>/polly/:id</b></pre>Friends and admin\nvote in Polly"]
    --> AdminClosesPolly["Admin closes polly"]
    --> PollyFinished

     NickNameInput:::UserInput
     CreateOrJoinTeam:::Decision
     CreateTeamInput:::UserInput
     JoinTeamInput:::UserInput
     RegisterPasskey:::UserInput
     IsAuthenticated:::Decision
     LoginInput:::UserInput
     TeamHome:::Aqua
     Polls:::Aqua
     PollShow:::Aqua
     PollStatus:::Decision
     CastVoteInput:::UserInput
     PollTitleInput:::UserInput
     AddPollyOptions:::UserInput
     NewUserRegistered@{ shape: dbl-circ, label: "New user<bR>registered" }
     LoggedIn@{ shape: dbl-circ, label: "Logged In" }
     StartVoting@{ shape: trap-b, label: "Admin starts voting phase" }
     EndVoting@{ shape: trap-t, label: "Admin ends voting phase" }
     PollFinished@{ shape: dbl-circ, label: "Poll FINSIHED" }
     BallotCasted@{ shape: dbl-circ, label: "Ballot counted<bR>successfully" }
     PollyFinished@{ shape: dbl-circ, label: "Polly is finished.\nWinner is\nshown" }
    classDef UserInput fill:#FFF,color:#333
    classDef Decision fill:#3F3,color:#333
    classDef Peach stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    classDef Pine stroke-width:1px, stroke-dasharray:none, stroke:#254336, fill:#27654A, color:#FFFFFF
    classDef Rose stroke-width:1px, stroke-dasharray:none, stroke:#FF5978, fill:#FFDFE5, color:#8E2236
    classDef Aqua stroke-width:1px, stroke-dasharray:none, stroke:#46EDC8, fill:#DEFFF8, color:#378E7A