/**
 * End-2-end HAPPY CASE test for liquido-mobile-pwa frontend.
 * This test runs through the easiest possible use case flow.
 * Only the successful "happy path" without any error cases or edge cases.
 * This test is completely standalone. It creates all the necessary test data along the way.
 * It does also not depend on any devLogin or workarounds. It tests the app completely as a black box form end user perspective.
 */

let now = Date.now() % 100000
console.log("Running Cypress HAPPY CASE test (team_id="+now+")", "NODE_ENV="+process.env.NODE_ENV)

const { expect } = require("chai");
//import { inspect } from 'util'  // better than JSON.stringify

let fix = {}  // Individual test fixtures for this test run. Every run can have its own test data.
	
/* When one of test steps fails, then abort the whole test run. */
afterEach(function() {
  if (this.currentTest.state === 'failed') {
		console.log("[ERROR] Cypress test step in happy case failed. Aborting.")
    Cypress.runner.stop()
  }
});

// testIsolation:false — the happy case is one sequential flow whose steps build on each other.
// The mocked backend keeps its "database" in sessionStorage (see liquido-graphql-client.mock.js).
// With Cypress' default testIsolation:true, sessionStorage is wiped before every test, which would
// discard the team/admin created in earlier steps and make the JWT re-login fail (JWT_TOKEN_INVALID).
context('LIQUIDO Happy Case', { testIsolation: false }, () => {

	/** 
	 * Create new test fixtures for each happy case test run. 
	 * Each happy case run creates a new team with a new admin and one new member.
	 */
	before(() => {
		fix.userName   = 'Cypress User-'+now
		fix.userEmail  = 'cypressUser-'+now+'@liquido.me'
		fix.userPassword = fix.userEmail + "pwd"
		// No mobilephone fixtures: a mobilephone is optional in LIQUIDO and no screen collects one,
		// so asserting on one here would only pretend to cover something.
		fix.adminName  = 'Cypress Admin-'+now
		fix.adminEmail = 'cypressAdmin-'+now+'@liquido.me'
		fix.adminPassword = fix.adminEmail + "pwd"
		fix.teamName   = 'Cypress Team '+now
		fix.pollTitle  = 'Cypress Poll '+now
		fix.proposalTitle  = 'Cypress Proposal '+now
		fix.proposalDescription = 'This proposal was generated by Cypress test id='+now+' Lorem ipsum best description ever that needs to be a bit longer because we want to test things like clipping and many more useless UX magic'
		fix.proposalTitle2  = 'Cypress Second Proposal '+now
		// Deliberately NOT a superset of proposalTitle2: the edit step asserts that the old
		// title is gone, and cy.contains() matches substrings.
		fix.proposalTitle2Edited = 'Cypress Edited Proposal '+now
		fix.pollTitleAdminOnly = 'Cypress Admin Only Poll '+now
		fix.proposalDescription2 = 'This proposal was generated by Cypress test id='+now+' Description of Second proposal. lorem ipsum best description ever that needs to be a bit long'
		// These values will be set during test steps
		fix.inviteCode = undefined
		fix.userJWT    = undefined
		fix.adminJWT   = undefined

		localStorage.removeItem("LIQUIDO_JWT")  // Make sure no one is logged in at the start
		sessionStorage.removeItem("LIQUIDO_MOCK_STATE") // Clear mock state
	})

	beforeEach(() => {
		console.log("===================================================")
		console.log("    TEST CASE >>>", Cypress.mocha.getRunner().suite.ctx.currentTest.title, "<<<")
		console.log("===================================================")
	})

	it('LIQIDO PWA is available', function() {
		cy.visit("/")
	})

	it('[Admin] Create new team', function() {
		//GIVEN some prepared test data
		assert.isString(fix.adminName)
		assert.isString(fix.teamName)
		assert.isString(fix.adminName)

		//WHEN we create a new team
		cy.visit("/")
		cy.get("#welcome-chat")
		cy.get('#userNameInput', {timeout: 8000}).type(fix.adminName).type("{enter}")    // implicitly checks that #userNameInput is not disabled
		
		cy.get('#createNewTeamButton').should('be.visible').click()  // Need to wait for button to become visible, because of andimation.
		cy.get('#teamNameInput').type(fix.teamName)
		cy.get('#adminEmailInput').type(fix.adminEmail)
		cy.get('#adminPasswordInput').type(fix.adminPassword)
		cy.intercept('POST', '**/login/welcomeMail').as('adminWelcomeMail')
		cy.get('#createNewTeamOkButton').click()

		//THEN new team is created successfully
		// #welcomeChatErrorModal does not exist anywhere in the app, so asserting it is absent could
		// never fail. The real error surface is the shared root popup.
		cy.get('#rootPopupModal').should('not.be.visible')

		// AND the admin got his welcome mail (fire-and-forget from welcome-chat.vue, so we only
		// assert that the backend was actually asked - the user is not blocked on it)
		cy.wait('@adminWelcomeMail').its('response.statusCode').should('eq', 200)
		cy.get('#newTeamCreatedBubble').should(() => {
			// AND a JWT was put into the browser's localStorage
			// (Cypress is async and crazy: This should()-block is retried until jwt is there.)
			fix.adminJWT = localStorage.getItem("LIQUIDO_JWT")
			expect(fix.adminJWT, "Expected to find a JWT in localStorage!").to.have.length.of.at.least(10)
		})
		
		// ===== Test passkey registration =====
		// GIVEN the setupPasskeyCard is shown
		cy.get('#setupPasskeyCard').should('be.visible')
		
		//  WHEN test-user tries to register his passkey
		cy.get('#passkeyInput').should('be.visible').clear().type('My Test Passkey')
		// AND we intercept the webauthn register request to make it fail    => no need to intercept. Will fail anyway :-)
		//cy.intercept('POST', '**/webauthn/register', {
		//	statusCode: 500,
		//	body: { error: 'Failed intentionally in test' }
		//})		
		cy.get('#setupPasskeyButton').should('be.visible').click()
				
		// THEN the passkey info modal is shown
		cy.get('#rootPopupModal').should('be.visible')
		
		// WHEN user clicks the secondary button ("Try again later") 
		cy.get('#modalSecondaryButton').click()
		
		// THEN the modal is closed
		cy.get('#rootPopupModal').should('not.be.visible')

		//  AND passkey label input is disabled
		cy.get('#passkeyInput').should('be.disabled')
		
		// AND the teamQrCode section is visible
		cy.get('#teamQrCode').should('be.visible')

		// AND there is an invite link with inviteCode
		// Here we extract the inviteCode, because we need it later to join this team.
		cy.get('#inviteCodeButton').invoke("attr", "data-invitecode").then(inviteCode => {   // "data-invitecode" attribute in lowercase!
			// Assert the real shape rather than "at least 2 chars", which would also accept "  " or "a-".
			// 8 alphanumerics mirrors config.inviteCodeLength on BOTH sides (frontend config.common.js
			// and backend LiquidoConfig) - deliberately duplicated here instead of importing config, so
			// that a silent change to either one is caught by this test.
			expect(inviteCode).to.match(/^[A-Za-z0-9]{8}$/, "InviteCode should be 8 alphanumeric characters")
			fix.inviteCode = inviteCode
			console.log("New team inviteCode=", fix.inviteCode)
			cy.log("InviteCode="+fix.inviteCode)
		})

	})

	it('[Admin] Returning admin is automatically logged in', function() {
		//GIVEN a team and a jwt
		assert.isString(fix.teamName, "Need to be logged into a team already.")
		assert.isString(fix.adminJWT, "Need adminJWT from last test step.")

		// WHEN we simulate that the jwt is stored in localStorage
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		//  AND admin visits the root start page
		cy.visit("/")
		// THEN we are automatically forwarded to correct team-home.
		cy.get("#team-home")
			.should("have.attr", "data-teamname", fix.teamName)
			.should("have.attr", "data-username", fix.adminName)

		// AND his name is shown in the list of team membres
		cy.get("#memberCircles").contains(fix.adminName)

		// AND being the team's admin, he sees the admin-only section.
		// This is the positive counterpart to the "should not exist" check in "[User] Join team": without
		// it, that negative assertion would still pass if the section vanished for everyone, and would
		// quietly stop proving anything about roles.
		cy.contains("Admin Einstellungen").should("be.visible")

		// AND his avatar image is loaded successfully
		//TODO: needs to be fixed with new teams homepage
		/*
		cy.get("#memberCards img").should('be.visible').and(($img) => {
			// "naturalWidth" and "naturalHeight" are set when the image was loaded
			expect($img[0].naturalWidth).to.be.greaterThan(1)
		})
			*/
	})

	it('[Admin] Create first poll and proposal', function() {
		assert.isString(fix.adminJWT, "Need adminJWT to create first poll")

		//GIVEN a logged in admin
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		cy.visit("/polls")
		cy.get('#createNewPollButton').click()

		// ============= create poll
		//GIVEN
		cy.get('#poll-create')
		//WHEN adding a poll
		cy.get('#pollTitleInput').type(fix.pollTitle)
		// The checkbox is OFF by default, so the admin must tick it - later steps in this
		// spec have an ordinary member add and edit a proposal in this very poll.
		cy.get('#membersCanAddProposalsInput').should('not.be.checked').check()
		cy.get('#createPollButton').click()
		//THEN newly created poll should be shown
		cy.get('#poll-show')
		cy.get('.poll-title').should('contain.text', fix.pollTitle)
		cy.get('#addProposalButton').should('be.visible')

		// ============ add first proposal
		//GIVEN a newly created poll
		cy.get('#addProposalButton').click()
		//WHEN adding a proposal
		cy.get('#propTitle').type(fix.proposalTitle)
		cy.get('#propDescription').type(fix.proposalDescription, { delay: 1 })
		cy.get('#saveProposalButton').click()
		cy.get('#modalPrimaryButton').click()
		//THEN the poll is shown with that proposal
		cy.get('#poll-show')
		cy.get('.proposal-title').should('contain.text', fix.proposalTitle)

	})
	
	it('[User] Join team', function() {
		//GIVEN inviteCode and data for new member
		assert.isString(fix.inviteCode, "Need inviteCode to test joinTeam")
		assert.isString(fix.userName)
		assert.isString(fix.userPassword)	
		assert.isString(fix.userEmail)
		assert.isString(fix.pollTitle, "Need existing poll to test joinTeam")
		assert.isString(fix.proposalTitle, "Need existing proposal to test joinTeam")

		//GIVEN user is not logged in
		cy.clearLocalStorage()   // just to be sure

		//WHEN joining a team
		cy.visit("/")
		cy.get('#userNameInput', {timeout: 8000}).type(fix.userName).type("{enter}")  // implicitly checks that #userNameInput is not disabled
		cy.get('#joinTeamButton').should('be.visible').click()
		cy.get('#inviteCodeInput').type(fix.inviteCode)
		cy.get('#userEmailInput').type(fix.userEmail)
		cy.get('#userPasswordInput').type(fix.userPassword)
		cy.intercept('POST', '**/login/welcomeMail').as('memberWelcomeMail')
		cy.get('#joinTeamOkButton').click()

		//THEN the join succeeded without any error surfacing
		cy.get('#rootPopupModal').should('not.be.visible')
		// AND the new member was sent his welcome mail
		cy.wait('@memberWelcomeMail').its('response.statusCode').should('eq', 200)

		// AND trying to register a passkey, after joining a team
		cy.get('#setupPasskeyCard').should('be.visible')
		cy.get('#passkeyInput').should('be.visible').clear().type('Join team passkey')
		cy.get('#setupPasskeyButton').should('be.visible').click()
		cy.get('#rootPopupModal').should('be.visible')
		cy.get('#modalSecondaryButton').click()
		cy.get('#rootPopupModal').should('not.be.visible')
		cy.get('#passkeyInput').should('be.disabled')		

		//THEN we can go to our team
		cy.get('#joinedTeamGoToTeamButton').click()

		// AND team-home is shown for joined user
		cy.get("#team-home")
			.should("have.attr", "data-teamname", fix.teamName)
			.should("have.attr", "data-username", fix.userName)

		// AND the team now has exactly the two of them - the admin who created it and this new member.
		// A member sees one circle per member; only an admin additionally gets the "einladen" circle.
		cy.get("#memberCircles .member-circle").should("have.length", 2)
		cy.get("#memberCircles").contains(fix.userName)
		cy.get("#memberCircles").contains(fix.adminName)

		// AND he joined as an ordinary MEMBER, not as an admin: the admin-only section is not there
		cy.contains("Admin Einstellungen").should("not.exist")

		cy.should(() => {
			// AND a JWT was put into the browser's localStorage
			// (Cypress is async and crazy: This should()-block is retried until jwt is there.)
			fix.userJWT = localStorage.getItem("LIQUIDO_JWT")
			expect(fix.userJWT, "Expected to find a JWT in localStorage!").to.have.length.of.at.least(10)
			// AND it is genuinely a different session than the admin's - otherwise every later
			// "[User] ..." step would silently be re-testing the admin.
			expect(fix.userJWT, "member JWT must differ from the admin's").to.not.equal(fix.adminJWT)
		})

		//WHEN navigating to team's polls
		cy.get("#gotoPollsButton").click()
		cy.get("#polls-page")

		//THEN our poll should be shown
		cy.get('.poll-title').should('contain.text', fix.pollTitle)

		//  AND as a plain member he cannot start the voting phase - that is the admin's job
		cy.contains(".poll-title", fix.pollTitle).click()
		cy.get('#poll-show')
		cy.get('#startVoteButton').should('not.exist')
	})

	
	it("[User] Show team and polls", function() {
		//GIVEN logged in user from that joined team
		assert.isString(fix.userJWT, "Need userJWT to show team and polls")
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)

		//WHEN logged in user opens the mobile app
		cy.visit("/")
		
		//THEN correct team-home is shown
		cy.get("#team-home")
			.should("have.attr", "data-teamname", fix.teamName)
			.should("have.attr", "data-username", fix.userName)

		//WHEN navigating to team's polls
		cy.get('#gotoPollsButton').click()
		//THEN then a poll with the created proposal from above should be found
		cy.get('.poll-title').should('contain.text', fix.pollTitle).click()
		cy.get('.proposal-title').should('contain.text', fix.proposalTitle)
		
		//cy.get('.poll-panel div.list-group').children('.proposal-list-group-item').should('have.length', 1)
	})

	it("[User] Member adds proposal", function() {
		assert.isString(fix.pollTitle, "Need existing poll to test joinTeam")
		assert.isString(fix.userJWT, "Need userJWT to show team and polls")

		//GIVEN a logged in member
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)
		cy.visit("/")

		//WHEN going to polls
		cy.get('#gotoPollsButton').click()
		//THEN we see our poll in elaboration with the correct title
		cy.contains(".poll-title", fix.pollTitle).click()
		
		// WHEN user adds a proposal
		cy.get("#addProposalButton").click()  // This might not be visible, when that user already added a proposal to the poll. => Not happy case
		cy.get("#propTitle").type(fix.proposalTitle2)
		cy.get("#propDescription").type(fix.proposalDescription2, { delay: 1 })
		cy.get("#saveProposalButton").click()
		cy.get('#modalPrimaryButton').click()
		
		//THEN the poll is shown with that proposal
		cy.get('#poll-show')
		cy.get('.proposal-title').should('contain.text', fix.proposalTitle2)
	})

	it("[User] Member edits his own proposal", function() {
		assert.isString(fix.userJWT, "Need userJWT to edit a proposal")
		assert.isString(fix.proposalTitle2, "Need the member's own proposal to edit it")

		//GIVEN a logged in member on the poll he added a proposal to
		// Use cy.window(), not a bare localStorage.setItem: the latter writes into the spec
		// runner's own storage, not the app's, so a JWT left over from the previous test wins.
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.userJWT))
		cy.visit("/")
		cy.get('#gotoPollsButton').click()
		cy.contains(".poll-title", fix.pollTitle).click()

		//THEN he has a pencil on his OWN proposal, but not on the admin's
		cy.contains('.proposal-list-group-item', fix.proposalTitle2).find('.edit-button').should('exist')
		cy.contains('.proposal-list-group-item', fix.proposalTitle).find('.edit-button').should('not.exist')

		//WHEN he edits his own proposal
		cy.contains('.proposal-list-group-item', fix.proposalTitle2).find('.edit-button').click()
		cy.get('#propTitle').clear().type(fix.proposalTitle2Edited)
		cy.get('#saveProposalButton').click()
		cy.get('#modalPrimaryButton').click()

		//THEN the poll shows the new title, and the old one is gone
		cy.get('#poll-show')
		cy.contains('.proposal-title', fix.proposalTitle2Edited).should('exist')
		cy.contains('.proposal-title', fix.proposalTitle2).should('not.exist')

		//AND it survives a reload - ie. it really was saved in the backend
		cy.reload()
		cy.contains('.proposal-title', fix.proposalTitle2Edited).should('exist')
	})

	// The DEFAULT path: the admin leaves "Teammitglieder dürfen Vorschläge hinzufügen" unchecked,
	// so he alone decides what is on the ballot.
	it("[Admin] Poll with the checkbox left off is admin-only", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to create an admin-only poll")
		assert.isString(fix.userJWT, "Need userJWT to check that a member may not add")

		//GIVEN a logged in admin creating a poll WITHOUT ticking the checkbox
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.adminJWT))
		cy.visit("/polls")
		cy.get('#createNewPollButton').click()
		cy.get('#poll-create')
		cy.get('#pollTitleInput').type(fix.pollTitleAdminOnly)
		cy.get('#membersCanAddProposalsInput').should('not.be.checked')   // off by default
		cy.get('#createPollButton').click()

		//THEN the admin himself may still add proposals
		cy.get('#poll-show')
		cy.get('.poll-title').should('contain.text', fix.pollTitleAdminOnly)
		cy.get('#addProposalButton').should('be.visible')

		//WHEN an ordinary member of the same team opens that poll
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.userJWT))
		cy.visit("/")
		cy.get('#gotoPollsButton').click()
		cy.contains(".poll-title", fix.pollTitleAdminOnly).click()

		//THEN he has no way to add a proposal, and is told why
		cy.get('#poll-show')
		cy.get('#addProposalButton').should('not.exist')
		cy.contains('nur der Admin').should('be.visible')
	})

	it("[User] User likes proposal", function() {
		assert.isString(fix.userJWT, "Need userJWT to like a proposal")
		assert.isString(fix.proposalTitle, "Need proposal title to like it")

		//GIVEN a logged in user
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)
		cy.visit("/")
		
		// WHEN navigating to poll -> proposal
		cy.get('#gotoPollsButton').click()
		cy.contains('.poll-title', fix.pollTitle).click()

		// I am still struggling to get used to thwat cypress commands yield.
		// Here we need to use a special syntax of contains. (And find instead of children *sic*) 
		// https://docs.cypress.io/api/commands/contains#Selector

		// THEN there are no likes yet
		cy.contains('.proposal-list-group-item', fix.proposalTitle).find('.numLikes')
			.should('have.text', 0)

			// WHEN clicking the like button
			.click()

		// THEN there should be exatly one like
		// Bugfix. Need to fetch the element again, because VUE exchanged the DOM elememnt.
		cy.contains('.proposal-list-group-item', fix.proposalTitle).find('.numLikes')
			.should('have.text', 1)
	})

	it("[Admin] Admin starts voting phase", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to show team and polls")

		//GIVEN a logged in admin
		cy.window().then((win) => {
			win.localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		})
		cy.visit("/")

		// AND the poll in elaboration that was created before
		cy.get('#gotoPollsButton').click()
		cy.contains(".poll-title", fix.pollTitle).click()

		// THEN the admin can STILL add a proposal, even though the poll already has several and is
		// ready to start. An admin may add proposals for as long as the poll is in ELABORATION - the
		// existing "[Admin] Poll with the checkbox left off is admin-only" step only covers a brand new
		// poll with no proposals yet, so this is the case that state does not reach.
		cy.get('#addProposalButton').should('be.visible')

		// WHEN admin starts the voting phase (the main action in the footer for a poll in ELABORATION)
		// Every GraphQL call shares one URL, so alias by inspecting the query body.
		cy.intercept('POST', '**/graphql', req => {
			if (req.body && req.body.query && req.body.query.includes('startVotingPhase')) {
				req.alias = 'startVotingPhase'
			}
		})
		cy.get("#startVoteButton").click()

		// THEN he must confirm first, because starting freezes the proposals
		// (scoped to this modal - the shared root popup uses the same button ids)
		cy.get('#startPollModal').should('be.visible')
		cy.get('#startPollModal').contains('keine Vorschläge mehr').should('be.visible')

		//  AND the runtime is prefilled from config.pollDefaultRuntimeDays
		cy.get('#pollDurationInput').should('have.value', '7')

		// WHEN he shortens it and confirms
		cy.get('#pollDurationInput').clear().type('3')
		cy.get('#startPollModal').find('#modalPrimaryButton').click()

		// THEN sucessModal is shown and poll is in status voting
		cy.get('#rootPopupModal').find('#modalPrimaryButton').click()
		cy.get(".poll-card[data-poll-status='VOTING']")
			.should("have.attr", "data-poll-status", "VOTING")

		//  AND the runtime he chose really reached the backend and was applied.
		//  Asserted on the intercepted call, because votingEndAt is not rendered anywhere on the page.
		cy.wait('@startVotingPhase').then(interception => {
			expect(interception.request.body.variables.durationInDays,
				"the duration from the dialog must be sent to the backend").to.equal(3)

			// votingEndAt is midnight of (today + days), so only the date part is meaningful.
			// Built from local date parts on purpose: toISOString() would convert to UTC and could
			// land on the neighbouring day depending on the timezone and the hour the test runs.
			const end = interception.response.body.data.startVotingPhase.votingEndAt
			const d = new Date()
			d.setDate(d.getDate() + 3)
			const pad = n => String(n).padStart(2, "0")
			const expectedDate = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
			expect(end.slice(0, 10), "poll must end 3 days from today, not after the 7 day default")
				.to.equal(expectedDate)
		})
	})

	
	it("[User] User casts vote", function() {
		assert.isString(fix.userJWT, "Need userJWT to show team and polls")

		//GIVEN a logged in member
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)
		cy.visit("/")
		
		// AND a poll in voting shown on team-home
		// Clicking a poll in voting on the team-home page navigates directly to cast-vote
		cy.get("#team-home")
		cy.get('.polls-in-voting-container').contains(".poll-title", fix.pollTitle).click()
		cy.get("#cast-vote-page")

		// AND both proposals have loaded into the "available proposals" pool.
		// We only check that they exist in the DOM (not that they are visible): the test helper below
		// is data-driven (it mutates Vue state, not the DOM), and an existence check is not affected
		// by the page slide transition or by the panel sitting below the fold.
		cy.get("#availableDraggable .proposal-panel").should("have.length", 2)

		// AND user drags a proposal into his ballot.
		// Native drag'n'drop (vuedraggable/SortableJS) is unreliable to simulate in Cypress,
		// so we use the test-only helper that cast-vote.vue exposes when window.Cypress is set.
		cy.window().then(win => {
			expect(win.liquidoCastVoteTest, "cast-vote test helper should be exposed on window").to.exist
			win.liquidoCastVoteTest.addFirstProposalToBallot()
		})

		// THEN the proposal appears in the ballot
		cy.get("#ballotDraggable .proposal-panel").should("have.length", 1)

		// WHEN user casts his vote
		cy.get("#castVoteButton").should("not.be.disabled").click()

		// THEN a confirmation modal is shown (cast-vote.vue's own confirmVoteModal)
		cy.get('#confirmVoteModal').should("be.visible")
		// WHEN user confirms the vote (scope to this modal to avoid duplicate #modalPrimaryButton IDs)
		cy.get('#confirmVoteModal').find('#modalPrimaryButton').click()
		
		// THEN root success modal is shown
		cy.get('#rootPopupModal').should("be.visible").and("have.attr", "data-modaltype", "success")
		// WHEN user clicks OK (navigates to poll-show via primaryCallback)
		cy.get('#rootPopupModal').find('#modalPrimaryButton').click()
		
		//  AND user is informed, that he can updated his ballot
		cy.get("#isUpdateableBallotInfo").should("be.visible")

		//WHEN verifing checksum
		cy.get("#verifyBallotButton").scrollIntoView().click({force: true})
		//THEN ballot is valid
		cy.get("#ballotIsVerifiedInfo").should("be.visible")
	})
	
	it("[Admin] Admin finishes voting phase", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to show team and polls")

		//GIVEN a logged in admin
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		cy.visit("/polls")
		// AND the poll in elaboration that was created before
		cy.contains(".poll-title", fix.pollTitle).click()

		// WHEN admin finishes the voting phase
		cy.get("#finishVoteButton").click()

		// THEN poll is FINISHED
		cy.get("#finishedPollInfo").should("be.visible")
		cy.get(".poll-card[data-poll-status='FINISHED']")
			.should("have.attr", "data-poll-status", "FINISHED")  
		//  AND there is exactly one winner (because we casted exactly one vote)
		cy.get(".poll-card .proposal-list-group-item.winner").should("have.length", 1)
	})

	it("[Admin] Poll winner page shows the winning proposal", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to view poll winner page")

		//GIVEN a logged in admin on the polls list
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		cy.visit("/polls")

		// WHEN clicking on the finished poll
		// FINISHED polls route directly to the poll winner page
		cy.contains(".poll-title", fix.pollTitle).click()

		// THEN the poll winner page is shown
		cy.get("#poll-winner-page").should("be.visible")

		// AND the winning proposal is displayed in the winner card
		cy.get(".winner-proposal").should("be.visible")
		cy.get(".winner-title").should("be.visible")
	})
	
	/* TODO
	it('cleanup DB', function() {
		
	})
	*/
	

})