/**
 * End-2-end HAPPY CASE test for liquido-mobile-pwa frontend.
 * This test runs through the easiest possible use case flow.
 * Only the successful "happy path" without any error cases or edge cases.
 * This test is completely standalone. It creates all the necessary test data along the way.
 * It does also not depend on any devLogin or workarounds. It tests the app completely as a black box form end user perspective.
 */

/*
 * A unique id per RUN, used to build every fixture below.
 *
 * This used to be `Date.now() % 100000`, which wraps every 100 seconds - two runs started ~100s
 * apart reused the same admin email, and team creation then died on a 401 that did not reproduce.
 * Full millisecond timestamp plus a random suffix: no wrap, no collision between parallel runs.
 */
const now = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
console.log("Running Cypress HAPPY CASE test (run id=" + now + ")")

// eslint-disable-next-line no-undef
const { expect } = require("chai")

let fix = {}  // Individual test fixtures for this test run. Every run can have its own test data.

/*
 * Row selectors for the poll editor (poll-card-edit.vue).
 *
 * Every row carries data-row-state="editing|saved". A row for a proposal that already exists in the
 * backend also carries data-proposal-id; the trailing "add another proposal" row does not, because
 * it has no id yet. That distinction matters: opening an existing proposal for editing leaves TWO
 * rows in state "editing" - the one you opened, and the empty one at the bottom.
 */
const SAVED_ROW    = '[data-row-state="saved"]'                        // an existing proposal, read only
const OPENED_ROW   = '[data-proposal-id][data-row-state="editing"]'    // an existing proposal, opened for editing
const NEW_ROW      = '.proposal-row:not([data-proposal-id])'           // the empty "add another" row
	
/* When one of test steps fails, then abort the whole test run. */
afterEach(function() {
  if (this.currentTest.state === 'failed') {
		console.log("[ERROR] Cypress test step in happy case failed. Aborting.")
    Cypress.runner.stop()
  }
});

// testIsolation:false — the happy case is one sequential flow whose steps build on each other.
// The mocked backend keeps its "database" in sessionStorage (see liquido-graphql-client.mock.js).
// With Cypress' default testIsolation:true, sessionStorage is wiped before every test, which would
// discard the team/admin created in earlier steps and make the JWT re-login fail (JWT_TOKEN_INVALID).
context('LIQUIDO Happy Case', { testIsolation: false }, () => {

	/** 
	 * Create new test fixtures for each happy case test run. 
	 * Each happy case run creates a new team with a new admin and one new member.
	 */
	before(() => {
		fix.userName   = 'Cypress User-'+now
		fix.userEmail  = 'cypressUser-'+now+'@liquido.me'
		fix.userPassword = fix.userEmail + "pwd"
		// No mobilephone fixtures: a mobilephone is optional in LIQUIDO and no screen collects one,
		// so asserting on one here would only pretend to cover something.
		fix.adminName  = 'Cypress Admin-'+now
		fix.adminEmail = 'cypressAdmin-'+now+'@liquido.me'
		fix.adminPassword = fix.adminEmail + "pwd"
		fix.teamName   = 'Cypress Team '+now
		fix.pollTitle  = 'Cypress Poll '+now
		// The admin's two proposals, both entered on the create page in one go.
		fix.proposalTitle  = 'Cypress Proposal '+now
		fix.proposalTitle2 = 'Cypress Second Proposal '+now
		// Descriptions must clear config.proposalDescriptionMinLength (20), which matches the
		// backend's @Size(min=20) on ProposalEntity.description.
		fix.proposalDescription = 'This proposal was generated by Cypress test id='+now+' Lorem ipsum best description ever that needs to be a bit longer because we want to test things like clipping and many more useless UX magic'
		fix.proposalDescription2 = 'This proposal was generated by Cypress test id='+now+' Description of Second proposal. lorem ipsum best description ever that needs to be a bit long'
		// A named icon, so the picker can be driven and the result asserted by class.
		fix.proposalIcon = 'hiking'
		// The admin adds this one only to delete it again.
		fix.proposalTitleToDelete = 'Cypress Doomed Proposal '+now
		// The member's own proposal, and its title after he edits it.
		fix.memberProposalTitle = 'Cypress Member Proposal '+now
		fix.memberProposalTitleEdited = 'Cypress Member Edited '+now
		fix.pollTitleAdminOnly = 'Cypress Admin Only Poll '+now
		// These values will be set during test steps
		fix.inviteCode = undefined
		fix.userJWT    = undefined
		fix.adminJWT   = undefined
		fix.pollId     = undefined
		fix.pollIdAdminOnly = undefined

		localStorage.removeItem("LIQUIDO_JWT")  // Make sure no one is logged in at the start
		sessionStorage.removeItem("LIQUIDO_MOCK_STATE") // Clear mock state
	})

	beforeEach(() => {
		console.log("===================================================")
		console.log("    TEST CASE >>>", Cypress.mocha.getRunner().suite.ctx.currentTest.title, "<<<")
		console.log("===================================================")
	})

	it('LIQIDO PWA is available', function() {
		cy.visit("/")
	})

	it('[Admin] Create new team', function() {
		//GIVEN some prepared test data
		assert.isString(fix.adminName)
		assert.isString(fix.teamName)
		assert.isString(fix.adminName)

		//WHEN we create a new team
		cy.visit("/")
		cy.get("#welcome-chat")
		cy.get('#userNameInput', {timeout: 8000}).type(fix.adminName).type("{enter}")    // implicitly checks that #userNameInput is not disabled
		
		cy.get('#createNewTeamButton').should('be.visible').click()  // Need to wait for button to become visible, because of andimation.
		cy.get('#teamNameInput').type(fix.teamName)
		cy.get('#adminEmailInput').type(fix.adminEmail)
		cy.get('#adminPasswordInput').type(fix.adminPassword)
		cy.intercept('POST', '**/login/welcomeMail').as('adminWelcomeMail')
		cy.get('#createNewTeamOkButton').click()

		//THEN new team is created successfully
		// #welcomeChatErrorModal does not exist anywhere in the app, so asserting it is absent could
		// never fail. The real error surface is the shared root popup.
		cy.get('#rootPopupModal').should('not.be.visible')

		// AND the admin got his welcome mail (fire-and-forget from welcome-chat.vue, so we only
		// assert that the backend was actually asked - the user is not blocked on it)
		cy.wait('@adminWelcomeMail').its('response.statusCode').should('eq', 200)
		cy.get('#newTeamCreatedBubble').should(() => {
			// AND a JWT was put into the browser's localStorage
			// (Cypress is async and crazy: This should()-block is retried until jwt is there.)
			fix.adminJWT = localStorage.getItem("LIQUIDO_JWT")
			expect(fix.adminJWT, "Expected to find a JWT in localStorage!").to.have.length.of.at.least(10)
		})
		
		// ===== Test passkey registration =====
		// GIVEN the setupPasskeyCard is shown
		cy.get('#setupPasskeyCard').should('be.visible')
		
		//  WHEN test-user tries to register his passkey
		cy.get('#passkeyInput').should('be.visible').clear().type('My Test Passkey')
		// AND we intercept the webauthn register request to make it fail    => no need to intercept. Will fail anyway :-)
		//cy.intercept('POST', '**/webauthn/register', {
		//	statusCode: 500,
		//	body: { error: 'Failed intentionally in test' }
		//})		
		cy.get('#setupPasskeyButton').should('be.visible').click()
				
		// THEN the passkey info modal is shown
		cy.get('#rootPopupModal').should('be.visible')
		
		// WHEN user clicks the secondary button ("Try again later") 
		cy.get('#rootPopupModalSecondaryButton').click()
		
		// THEN the modal is closed
		cy.get('#rootPopupModal').should('not.be.visible')

		//  AND passkey label input is disabled
		cy.get('#passkeyInput').should('be.disabled')
		
		// AND the teamQrCode section is visible
		cy.get('#teamQrCode').should('be.visible')

		// AND there is an invite link with inviteCode
		// Here we extract the inviteCode, because we need it later to join this team.
		cy.get('#inviteCodeButton').invoke("attr", "data-invitecode").then(inviteCode => {   // "data-invitecode" attribute in lowercase!
			// Assert the real shape rather than "at least 2 chars", which would also accept "  " or "a-".
			// 8 alphanumerics mirrors config.inviteCodeLength on BOTH sides (frontend config.common.js
			// and backend LiquidoConfig) - deliberately duplicated here instead of importing config, so
			// that a silent change to either one is caught by this test.
			expect(inviteCode).to.match(/^[A-Za-z0-9]{8}$/, "InviteCode should be 8 alphanumeric characters")
			fix.inviteCode = inviteCode
			console.log("New team inviteCode=", fix.inviteCode)
			cy.log("InviteCode="+fix.inviteCode)
		})

	})

	it('[Admin] Returning admin is automatically logged in', function() {
		//GIVEN a team and a jwt
		assert.isString(fix.teamName, "Need to be logged into a team already.")
		assert.isString(fix.adminJWT, "Need adminJWT from last test step.")

		// WHEN we simulate that the jwt is stored in localStorage
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		//  AND admin visits the root start page
		cy.visit("/")
		// THEN we are automatically forwarded to correct team-home.
		cy.get("#team-home")
			.should("have.attr", "data-teamname", fix.teamName)
			.should("have.attr", "data-username", fix.adminName)

		// AND his name is shown in the list of team membres
		cy.get(`#memberCircles [data-member-name="${fix.adminName}"]`).should('exist')

		// AND being the team's admin, he sees the admin-only section.
		// This is the positive counterpart to the "should not exist" check in "[User] Join team": without
		// it, that negative assertion would still pass if the section vanished for everyone, and would
		// quietly stop proving anything about roles.
		// scrollIntoView: team-home is taller than a phone screen (polls in voting, the passkey alert
		// and the verify-email reminder all sit above this), and should('be.visible') never scrolls.
		cy.get("#adminSettingsSection").scrollIntoView().should("be.visible")

		// AND because he has just registered, his address is not confirmed yet, so the reminder is
		// there - with the inline "send me a new one" link rather than a button.
		cy.get("#verifyEmailReminder").scrollIntoView().should("be.visible")
		cy.get("#resendEmailVerificationLink").should("exist")

		// AND his avatar image is loaded successfully
		//TODO: needs to be fixed with new teams homepage
		/*
		cy.get("#memberCards img").should('be.visible').and(($img) => {
			// "naturalWidth" and "naturalHeight" are set when the image was loaded
			expect($img[0].naturalWidth).to.be.greaterThan(1)
		})
			*/
	})

	it('[Admin] Create a poll with its first two proposals on one page', function() {
		assert.isString(fix.adminJWT, "Need adminJWT to create first poll")

		//GIVEN a logged in admin
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		cy.visit("/polls")
		cy.get('#createNewPollButton').click()

		//THEN the all-in-one editor opens, already showing the two proposal rows a poll needs
		cy.get('#poll-edit')
		cy.get(NEW_ROW).should('have.length', 2)
		cy.get(SAVED_ROW).should('not.exist')
		cy.get('#addProposalRowButton').should('be.visible')
		// AND with nothing filled in yet, the poll cannot be created
		cy.get('#createPollButton').should('be.disabled')

		//WHEN the admin fills in the title and both proposals
		cy.get('#pollTitleInput').type(fix.pollTitle)
		cy.get('#proposalTitleInput-0').type(fix.proposalTitle)
		cy.get('#proposalDescriptionInput-0').type(fix.proposalDescription, { delay: 1 })
		cy.get('#proposalTitleInput-1').type(fix.proposalTitle2)
		cy.get('#proposalDescriptionInput-1').type(fix.proposalDescription2, { delay: 1 })

		// AND picks a specific icon for the first one, to prove the picker reaches the backend
		cy.get('#proposalIconButton-0').click()
		cy.get('#iconPickerModal').should('be.visible')
		cy.get('#iconSearchInput').type(fix.proposalIcon)
		cy.get(`.icon-in-list .fa-${fix.proposalIcon}`).click()
		cy.get('#iconPickerModalPrimaryButton').click()
		cy.get('#proposalIconButton-0 i').should('have.class', `fa-${fix.proposalIcon}`)

		// AND ticks the box, because later steps have an ordinary member add a proposal to this poll
		cy.get('#membersCanAddProposalsInput').should('not.be.checked').check()

		//THEN the poll can now be created
		cy.get('#createPollButton').should('not.be.disabled').click()

		//THEN the newly created poll is shown, with BOTH proposals from that one page
		cy.get('#poll-show')
		cy.url().should('match', /\/polls\/\d+$/).then(url => {
			fix.pollId = url.split('/').pop()
		})
		cy.get('.poll-card .proposal-list-group-item').should('have.length', 2)
		cy.get('#addProposalButton').should('be.visible')

		// AND the chosen icon really was saved, not just shown in the editor
		cy.get('.poll-card .proposal-list-group-item').first()
			.find('.proposal-icon i').should('have.class', `fa-${fix.proposalIcon}`)

		// AND both proposals survive a reload, ie. they reached the backend
		cy.reload()
		cy.get('.poll-card .proposal-list-group-item').should('have.length', 2)
	})

	it('[Admin] Admin may delete a proposal, and add another, while the poll is in ELABORATION', function() {
		assert.isString(fix.adminJWT, "Need adminJWT to edit the poll")
		assert.isString(fix.pollId, "Need the poll created above")

		//GIVEN the admin in the editor of his own poll
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.adminJWT))
		cy.visit(`/polls/${fix.pollId}/edit`)
		cy.get('#poll-edit')

		//THEN both proposals are shown saved, plus one empty row to add another
		cy.get(SAVED_ROW).should('have.length', 2)
		cy.get(NEW_ROW).should('have.length', 1)

		//WHEN the admin adds a third proposal that he will then delete again
		cy.get('#proposalTitleInput-2').type(fix.proposalTitleToDelete)
		cy.get('#proposalDescriptionInput-2').type(fix.proposalDescription, { delay: 1 })
		cy.get('#saveProposalButton-2').should('not.be.disabled').click()

		//THEN it is saved and the editor offers a fresh empty row again
		cy.get(SAVED_ROW).should('have.length', 3)
		cy.get(NEW_ROW).should('have.length', 1)

		//WHEN he deletes it again
		cy.get(SAVED_ROW).eq(2).find('[id^=deleteProposalButton-]').click()
		cy.get('#confirmDeleteModal').should('be.visible')
		cy.get('#confirmDeleteModalPrimaryButton').click()

		//THEN it is gone, and the two original proposals remain
		cy.get(SAVED_ROW).should('have.length', 2)

		// AND the deletion really reached the backend
		cy.reload()
		cy.get(SAVED_ROW).should('have.length', 2)
	})

	it('[User] Join team', function() {
		//GIVEN inviteCode and data for new member
		assert.isString(fix.inviteCode, "Need inviteCode to test joinTeam")
		assert.isString(fix.userName)
		assert.isString(fix.userPassword)	
		assert.isString(fix.userEmail)
		assert.isString(fix.pollTitle, "Need existing poll to test joinTeam")
		assert.isString(fix.proposalTitle, "Need existing proposal to test joinTeam")

		//GIVEN user is not logged in
		cy.clearLocalStorage()   // just to be sure

		//WHEN joining a team
		cy.visit("/")
		cy.get('#userNameInput', {timeout: 8000}).type(fix.userName).type("{enter}")  // implicitly checks that #userNameInput is not disabled
		cy.get('#joinTeamButton').should('be.visible').click()
		cy.get('#inviteCodeInput').type(fix.inviteCode)
		cy.get('#userEmailInput').type(fix.userEmail)
		cy.get('#userPasswordInput').type(fix.userPassword)
		cy.intercept('POST', '**/login/welcomeMail').as('memberWelcomeMail')
		cy.get('#joinTeamOkButton').click()

		//THEN the join succeeded without any error surfacing
		cy.get('#rootPopupModal').should('not.be.visible')
		// AND the new member was sent his welcome mail
		cy.wait('@memberWelcomeMail').its('response.statusCode').should('eq', 200)

		// AND trying to register a passkey, after joining a team
		cy.get('#setupPasskeyCard').should('be.visible')
		cy.get('#passkeyInput').should('be.visible').clear().type('Join team passkey')
		cy.get('#setupPasskeyButton').should('be.visible').click()
		cy.get('#rootPopupModal').should('be.visible')
		cy.get('#rootPopupModalSecondaryButton').click()
		cy.get('#rootPopupModal').should('not.be.visible')
		cy.get('#passkeyInput').should('be.disabled')		

		//THEN we can go to our team
		cy.get('#joinedTeamGoToTeamButton').click()

		// AND team-home is shown for joined user
		cy.get("#team-home")
			.should("have.attr", "data-teamname", fix.teamName)
			.should("have.attr", "data-username", fix.userName)

		// AND the team now has exactly the two of them - the admin who created it and this new member.
		// A member sees one circle per member; only an admin additionally gets the "einladen" circle.
		cy.get("#memberCircles [data-member-name]").should("have.length", 2)
		// AND he is a MEMBER, the team's creator is the ADMIN
		cy.get(`#memberCircles [data-member-name="${fix.userName}"]`).should('have.attr', 'data-member-role', 'MEMBER')
		cy.get(`#memberCircles [data-member-name="${fix.adminName}"]`).should('have.attr', 'data-member-role', 'ADMIN')
		cy.get(`#memberCircles [data-member-name="${fix.userName}"]`).should('exist')
		cy.get(`#memberCircles [data-member-name="${fix.adminName}"]`).should('exist')

		// AND he joined as an ordinary MEMBER, not as an admin: the admin-only section is not there
		cy.get("#adminSettingsSection").should("not.exist")

		cy.should(() => {
			// AND a JWT was put into the browser's localStorage
			// (Cypress is async and crazy: This should()-block is retried until jwt is there.)
			fix.userJWT = localStorage.getItem("LIQUIDO_JWT")
			expect(fix.userJWT, "Expected to find a JWT in localStorage!").to.have.length.of.at.least(10)
			// AND it is genuinely a different session than the admin's - otherwise every later
			// "[User] ..." step would silently be re-testing the admin.
			expect(fix.userJWT, "member JWT must differ from the admin's").to.not.equal(fix.adminJWT)
		})

		//WHEN navigating to team's polls
		cy.get("#gotoPollsButton").click()
		cy.get("#polls-page")

		//THEN our poll should be shown
		cy.get(`[data-poll-id="${fix.pollId}"]`).should('exist')

		//  AND as a plain member he cannot start the voting phase - that is the admin's job
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()
		cy.get('#poll-show')
		cy.get('#startVoteButton').should('not.exist')
		//  AND a poll in ELABORATION offers exactly ONE footer action. For a member that is Back:
		//  there is nothing else for them to do there, and two competing primary buttons is a bug.
		cy.get('#backToPollsButton').should('exist')
	})

	
	it("[User] Show team and polls", function() {
		//GIVEN logged in user from that joined team
		assert.isString(fix.userJWT, "Need userJWT to show team and polls")
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)

		//WHEN logged in user opens the mobile app
		cy.visit("/")
		
		//THEN correct team-home is shown
		cy.get("#team-home")
			.should("have.attr", "data-teamname", fix.teamName)
			.should("have.attr", "data-username", fix.userName)

		//WHEN navigating to team's polls
		cy.get('#gotoPollsButton').click()
		//THEN the poll created above is listed, and opens with both of the admin's proposals
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()
		cy.get('#poll-show')
		cy.get('.poll-card .proposal-list-group-item').should('have.length', 2)
	})

	it("[User] Member adds his own proposal in the editor", function() {
		assert.isString(fix.userJWT, "Need userJWT to add a proposal")
		assert.isString(fix.pollId, "Need the poll created above")

		//GIVEN a logged in member on the poll the admin opened up
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.userJWT))
		cy.visit("/")
		cy.get('#gotoPollsButton').click()
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()
		cy.get('#poll-show')

		//WHEN he follows "add a proposal" into the editor
		cy.get("#addProposalButton").click()
		cy.get('#poll-edit')

		//THEN the poll's title is NOT editable for him - only the admin may rename a poll
		cy.get('#pollTitleInput').should('not.exist')
		// AND the admin's two proposals are read only, with exactly one empty row for his own
		cy.get(SAVED_ROW).should('have.length', 2)
		cy.get(NEW_ROW).should('have.length', 1)
		cy.get(OPENED_ROW).should('not.exist')
		// AND he may not delete anybody's proposal
		cy.get('[id^=deleteProposalButton-]').should('not.exist')
		// AND he may not edit the admin's proposals either
		cy.get('[id^=editProposalButton-]').should('not.exist')

		//WHEN he fills in his proposal
		cy.get('#proposalTitleInput-2').type(fix.memberProposalTitle)
		// A too short description must not be acceptable - the backend would reject it anyway
		cy.get('#proposalDescriptionInput-2').type('too short')
		cy.get('#saveProposalButton-2').should('be.disabled')
		cy.get('#proposalDescriptionInput-2').clear().type(fix.proposalDescription2, { delay: 1 })
		cy.get('#saveProposalButton-2').should('not.be.disabled').click()

		//THEN the poll now holds three proposals, and a fresh empty row is offered
		cy.get(SAVED_ROW).should('have.length', 3)
		cy.get(NEW_ROW).should('have.length', 1)

		// AND it survived the round trip to the backend
		cy.reload()
		cy.get(SAVED_ROW).should('have.length', 3)
	})

	it("[User] Member edits his own proposal, and only his own", function() {
		assert.isString(fix.userJWT, "Need userJWT to edit a proposal")
		assert.isString(fix.pollId, "Need the poll created above")

		//GIVEN a logged in member on that poll
		// Use cy.window(), not a bare localStorage.setItem: the latter writes into the spec
		// runner's own storage, not the app's, so a JWT left over from the previous test wins.
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.userJWT))
		cy.visit(`/polls/${fix.pollId}`)
		cy.get('#poll-show')

		//THEN he has a pencil on his OWN proposal, and on no other
		cy.get('.poll-card .proposal-list-group-item').should('have.length', 3)
		cy.get('.poll-card .edit-button').should('have.length', 1)

		//WHEN he clicks it, he lands in the editor with exactly that row already open
		cy.get('.poll-card .edit-button').click()
		cy.get('#poll-edit')
		cy.get(OPENED_ROW).should('have.length', 1)
		// AND the field is prefilled with what he wrote
		cy.get(OPENED_ROW).find('input[id^=proposalTitleInput-]')
			.should('have.value', fix.memberProposalTitle)

		//WHEN he rewrites the title and saves
		cy.get(OPENED_ROW).find('input[id^=proposalTitleInput-]')
			.clear().type(fix.memberProposalTitleEdited)
		cy.get(OPENED_ROW).find('button[id^=saveProposalButton-]').click()

		//THEN the poll still has three proposals - an edit must not create a fourth
		cy.get(SAVED_ROW).should('have.length', 3)
		cy.get(OPENED_ROW).should('not.exist')

		//AND the new title survives a reload, ie. it really was saved in the backend
		cy.reload()
		cy.get('#poll-edit')
		cy.get('.poll-card-edit .edit-button').click()
		cy.get(OPENED_ROW).find('input[id^=proposalTitleInput-]')
			.should('have.value', fix.memberProposalTitleEdited)
	})

	// The DEFAULT path: the admin leaves the checkbox unticked, so he alone decides the ballot.
	it("[Admin] Poll with the checkbox left off is admin-only", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to create an admin-only poll")
		assert.isString(fix.userJWT, "Need userJWT to check that a member may not add")

		//GIVEN a logged in admin creating a poll WITHOUT ticking the checkbox
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.adminJWT))
		cy.visit("/polls")
		cy.get('#createNewPollButton').click()
		cy.get('#poll-edit')
		cy.get('#pollTitleInput').type(fix.pollTitleAdminOnly)
		cy.get('#proposalTitleInput-0').type(fix.proposalTitle)
		cy.get('#proposalDescriptionInput-0').type(fix.proposalDescription, { delay: 1 })
		cy.get('#proposalTitleInput-1').type(fix.proposalTitle2)
		cy.get('#proposalDescriptionInput-1').type(fix.proposalDescription2, { delay: 1 })
		cy.get('#membersCanAddProposalsInput').should('not.be.checked')   // off by default
		cy.get('#createPollButton').click()

		//THEN the admin himself may still add proposals
		cy.get('#poll-show')
		cy.url().should('match', /\/polls\/\d+$/).then(url => {
			fix.pollIdAdminOnly = url.split('/').pop()
		})
		cy.get('#addProposalButton').should('be.visible')

		//WHEN an ordinary member of the same team opens that poll
		cy.window().then(win => win.localStorage.setItem("LIQUIDO_JWT", fix.userJWT))
		cy.visit("/")
		cy.get('#gotoPollsButton').click()
		cy.then(() => {
			cy.get(`[data-poll-id="${fix.pollIdAdminOnly}"]`).click()
		})

		//THEN he has no way to add a proposal, and is told why
		cy.get('#poll-show')
		cy.get('#addProposalButton').should('not.exist')
		cy.get('#onlyAdminAddsProposalsInfo').scrollIntoView().should('be.visible')

		//AND even reaching the editor by URL gives him no row to type in
		cy.then(() => {
			cy.visit(`/polls/${fix.pollIdAdminOnly}/edit`)
		})
		cy.get('#poll-edit')
		cy.get(NEW_ROW).should('not.exist')
		cy.get(OPENED_ROW).should('not.exist')
		cy.get('#onlyAdminAddsProposalsInfo').scrollIntoView().should('be.visible')
	})

	it("[User] User likes proposal", function() {
		assert.isString(fix.userJWT, "Need userJWT to like a proposal")
		assert.isString(fix.proposalTitle, "Need proposal title to like it")

		//GIVEN a logged in user
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)
		cy.visit("/")
		
		// WHEN navigating to poll -> proposal
		cy.get('#gotoPollsButton').click()
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()

		// I am still struggling to get used to thwat cypress commands yield.
		// Here we need to use a special syntax of contains. (And find instead of children *sic*) 
		// https://docs.cypress.io/api/commands/contains#Selector

		// THEN there are no likes yet
		cy.get('.poll-card .proposal-list-group-item').first().find('.numLikes')
			.should('have.text', 0)

			// WHEN clicking the like button
			.click()

		// THEN there should be exatly one like
		// Bugfix. Need to fetch the element again, because VUE exchanged the DOM elememnt.
		cy.get('.poll-card .proposal-list-group-item').first().find('.numLikes')
			.should('have.text', 1)
	})

	it("[Admin] Admin starts voting phase", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to show team and polls")

		//GIVEN a logged in admin
		cy.window().then((win) => {
			win.localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		})
		cy.visit("/")

		// AND the poll in elaboration that was created before
		cy.get('#gotoPollsButton').click()
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()

		// THEN the admin can STILL add a proposal, even though the poll already has several and is
		// ready to start. An admin may add proposals for as long as the poll is in ELABORATION - the
		// existing "[Admin] Poll with the checkbox left off is admin-only" step only covers a brand new
		// poll with no proposals yet, so this is the case that state does not reach.
		// scrollIntoView first: the poll card with several proposals is taller than a 375x667 phone
		// screen, so this button starts below the fold. should('be.visible') never scrolls by itself.
		cy.get('#addProposalButton').scrollIntoView().should('be.visible')

		// AND the footer offers exactly one action - starting the vote. The admin must NOT also get a
		// Back button next to it: one poll state, one primary action.
		cy.get('#startVoteButton').should('exist')
		cy.get('#backToPollsButton').should('not.exist')

		// WHEN admin starts the voting phase (the main action in the footer for a poll in ELABORATION)
		// Every GraphQL call shares one URL, so alias by inspecting the query body.
		cy.intercept('POST', '**/graphql', req => {
			if (req.body && req.body.query && req.body.query.includes('startVotingPhase')) {
				req.alias = 'startVotingPhase'
			}
		})
		cy.get("#startVoteButton").click()

		// THEN he must confirm first, because starting freezes the proposals
		// (scoped to this modal - the shared root popup uses the same button ids)
		cy.get('#startPollModal').should('be.visible')
		cy.get('#startPollConfirmMessage').should('be.visible')

		//  AND the runtime is prefilled from config.pollDefaultRuntimeDays
		cy.get('#pollDurationInput').should('have.value', '7')

		// WHEN he shortens it and confirms
		cy.get('#pollDurationInput').clear().type('3')
		cy.get('#startPollModalPrimaryButton').click()

		// THEN sucessModal is shown and poll is in status voting
		cy.get('#rootPopupModalPrimaryButton').click()
		cy.get(".poll-card[data-poll-status='VOTING']")
			.should("have.attr", "data-poll-status", "VOTING")

		//  AND the runtime he chose really reached the backend and was applied.
		//  Asserted on the intercepted call, because votingEndAt is not rendered anywhere on the page.
		cy.wait('@startVotingPhase').then(interception => {
			expect(interception.request.body.variables.durationInDays,
				"the duration from the dialog must be sent to the backend").to.equal(3)

			// votingEndAt is midnight of (today + days), so only the date part is meaningful.
			// Built from local date parts on purpose: toISOString() would convert to UTC and could
			// land on the neighbouring day depending on the timezone and the hour the test runs.
			const end = interception.response.body.data.startVotingPhase.votingEndAt
			const d = new Date()
			d.setDate(d.getDate() + 3)
			const pad = n => String(n).padStart(2, "0")
			const expectedDate = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
			expect(end.slice(0, 10), "poll must end 3 days from today, not after the 7 day default")
				.to.equal(expectedDate)
		})
	})

	
	it("[User] User casts vote", function() {
		assert.isString(fix.userJWT, "Need userJWT to show team and polls")

		//GIVEN a logged in member
		localStorage.setItem("LIQUIDO_JWT", fix.userJWT)
		cy.visit("/")
		
		// AND a poll in voting shown on team-home
		// Clicking a poll in voting on the team-home page navigates directly to cast-vote
		cy.get("#team-home")
		cy.get(`.polls-in-voting-container [data-poll-id="${fix.pollId}"]`).click()
		cy.get("#cast-vote-page")

		// AND all three proposals have loaded into the "available proposals" pool:
		// the admin's two from the create page, plus the one this member added. (The admin also added
		// a fourth earlier and deleted it again, which is why the count is three and not four.)
		// We only check that they exist in the DOM (not that they are visible): the test helper below
		// is data-driven (it mutates Vue state, not the DOM), and an existence check is not affected
		// by the page slide transition or by the panel sitting below the fold.
		cy.get("#availableDraggable .proposal-panel").should("have.length", 3)

		// AND user drags a proposal into his ballot.
		// Native drag'n'drop (vuedraggable/SortableJS) is unreliable to simulate in Cypress,
		// so we use the test-only helper that cast-vote.vue exposes when window.Cypress is set.
		cy.window().then(win => {
			expect(win.liquidoCastVoteTest, "cast-vote test helper should be exposed on window").to.exist
			win.liquidoCastVoteTest.addFirstProposalToBallot()
		})

		// THEN the proposal appears in the ballot
		cy.get("#ballotDraggable .proposal-panel").should("have.length", 1)

		// WHEN user casts his vote
		cy.get("#castVoteButton").should("not.be.disabled").click()

		// THEN a confirmation modal is shown (cast-vote.vue's own confirmVoteModal)
		cy.get('#confirmVoteModal').should("be.visible")
		// WHEN user confirms the vote
		cy.get('#confirmVoteModalPrimaryButton').click()
		
		// THEN root success modal is shown
		cy.get('#rootPopupModal').should("be.visible").and("have.attr", "data-modaltype", "success")
		// WHEN user clicks OK (navigates to poll-show via primaryCallback)
		cy.get('#rootPopupModalPrimaryButton').click()
		
		//  AND user is informed, that he can updated his ballot
		cy.get("#alreadyVotedInfo").scrollIntoView().should("be.visible")

		//WHEN verifing checksum
		cy.get("#verifyBallotButton").scrollIntoView().click({force: true})
		//THEN ballot is valid
		cy.get("#ballotIsVerifiedInfo").scrollIntoView().should("be.visible")
	})
	
	it("[Admin] Admin finishes voting phase", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to show team and polls")

		//GIVEN a logged in admin
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		cy.visit("/polls")
		// AND the poll in elaboration that was created before
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()

		// WHEN admin finishes the voting phase
		cy.get("#finishVoteButton").click()

		// THEN poll is FINISHED
		cy.get("#finishedPollInfo").scrollIntoView().should("be.visible")
		cy.get(".poll-card[data-poll-status='FINISHED']")
			.should("have.attr", "data-poll-status", "FINISHED")  
		//  AND there is exactly one winner (because we casted exactly one vote)
		cy.get(".poll-card .proposal-list-group-item.winner").should("have.length", 1)
	})

	it("[Admin] Poll winner page shows the winning proposal", function() {
		assert.isString(fix.adminJWT, "Need adminJWT to view poll winner page")

		//GIVEN a logged in admin on the polls list
		localStorage.setItem("LIQUIDO_JWT", fix.adminJWT)
		cy.visit("/polls")

		// WHEN clicking on the finished poll
		// FINISHED polls route directly to the poll winner page
		cy.get(`[data-poll-id="${fix.pollId}"]`).click()

		// THEN the poll winner page is shown
		cy.get("#poll-winner-page").should("be.visible")

		// AND the winning proposal is displayed in the winner card
		cy.get(".winner-proposal").should("be.visible")
		cy.get(".winner-title").should("be.visible")
	})
	
	/* TODO
	it('cleanup DB', function() {
		
	})
	*/
	

})